### ISSUE TITLE
record_array.cc 의 37번줄 tpye 비교를 왜 int로 했는지 잘 모르겠습니다

### ISSUE THREAD

**Issue by wjdrud2532** [special-c-vessel/Replay#1]
기록할 때 모든 타입은 i8, i16 .. 형식으로 기록하는데
왜 int로 비교하는건지 잘 모르겠습니다.

**Comment by yongilkim01** [comment]
개발 중 임시로 작성한 코드입니다.

**Comment by wjdrud2532** [comment]
기능을 하지 않고 임시로 작성한 코드라면 그에 맞는 주석을 작성해주세요
기능 개발 예정이라면 어떤 기능을 할 것인지 까지 작성해주세요
