### ISSUE TITLE
벡터 기록을 함수로 구현하는 것도 좋지만

### ISSUE THREAD

**Issue by wjdrud2532** [special-c-vessel/Replay#5]
map, queue 같이 다른 구조를 기록하게 되면
그때마다 새로운 함수를 만들어야 하기 때문에 앞으로의 유지보수나 기능 개발이 많이 힘들겁니다

1학기 말부터 방학 내내 교수님이랑 저랑 계속 이야기 하던게 이거에요.

이 부분을 어떻게 처리할 것인가 -> 기록과 재현 단계를 같이 고려해 봐야한다 -> 개발 균형이 중요하다 
이렇게 된겁니다

그동안 형도 옆에서 들으면서 나름 생각해 본게 있을겁니다.
개발할 때 참고하시고, 같이 한번 생각해 봅시다.

**Comment by yongilkim01** [comment]
네 알겠습니다.
